{
 "title": "Home Information",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Allergen Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "airpure_allergen", "legendFormat": "AC3829" }
   ]
  },
  {
   "title": "Indoor PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "airpure_pm25", "legendFormat": "AC3829" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "airpure_temp", "legendFormat": "AC3829" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "airpure_humidity", "legendFormat": "AC3829" }
   ]
  },
  {
   "title": "Internet Connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "speedtest_down", "legendFormat": "Download" },
    { "expr": "speedtest_up", "legendFormat": "Upload" }
   ]
  }
 ]
}