version: "3"

networks:
    grafana:

volumes:
    prom_volume:
    grafana_data:

services:
    grafana:
        image: grafana/grafana
        volumes:
            - grafana_data:/var/lib/grafana
        ports: 
            - 3000:3000
        networks:
            - grafana
        restart: unless-stopped

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/:/etc/prometheus
            - prom_volume:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - 9090:9090
        networks:
            - grafana
        restart: unless-stopped