global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "speedtest"

    # Override global settings
    scrape_interval: 1m

    static_configs:
      - targets: ["host.docker.internal:8001"]

  - job_name: "airpure"

    # Override global settings
    scrape_interval: 1m

    static_configs:
      - targets: ["host.docker.internal:8002"]
